### ISSUE TITLE
谷歌提交出现错误

### ISSUE THREAD

**Issue by ASC8384** [JohnStinky/Sitemap-for-Typecho#1]
1. 站点地图可读取，但存在错误
2. 您的 Sitemap 显示为 HTML 网页。请使用受支持的 Sitemap 格式
3. 第 2行|标记：|html

[我的sitemap](https://asc8384.top/sitemap.xml)

**Comment by jozhn** [comment]
谢谢提醒，有空我修改一下

**Comment by ASC8384** [comment]
感觉谷歌好像只收[这种类型](https://www.typecho.wiki/sitemap.xml)的

**Comment by jozhn** [comment]
修改之后现在符合Google标准了
